### ISSUE TITLE
Compute the characteristic polynomial of frobenius

### ISSUE THREAD

**Issue by kevinywlui** [williamstein/sage_modabvar#6]
read section 3.5 of http://wstein.org/papers/shacomp/

**Comment by kevinywlui** [comment]
Also implement the torsion bound from the same section.

**Comment by kevinywlui** [comment]
#11

**Comment by williamstein** [comment]
I was confused why in the code in https://github.com/williamstein/sage_modabvar/pull/24 you use Lagrange interpolation and compute up and down a tower of finite fields, etc.   Observe:

```
sage: from sage_modabvar import J0, J1
sage: J=J0(23)
sage: J.frobenius_polynomial(997)
x^4 + 20*x^3 + 1374*x^2 + 19940*x + 994009
sage: f = J.hecke_polynomial(997)
sage: g = SR(f)
sage: expand(g(x+997/x)*x^2)
x^4 + 20*x^3 + 1374*x^2 + 19940*x + 994009
```

There is a **simple relationship** between the charpoly of Frob and the charpoly of T_p.  That's what we use in the first place to derive section 3.5 of the shacomp paper.  It is a consequence of the Eichler-Shimura theorem, which says Ver_p+Frob_p = T_p.    The relationship is simply that if $f$ is the charpoly of $T_p$, then $f(x + p/x)x^d$ is the charpoly of Frob.

**Comment by kevinywlui** [comment]
> The relationship is simply that if $f$ is the charpoly of $T_p$, then $f(x + p/x)x^d$ is the charpoly of Frob.

Okay I'll use this. Just to be sure, for Gamma1, it'll be $f(x + \epsilon(p)*p/x)x^d$ with $\epsilon$ the character of the newform right?

**Comment by kevinywlui** [comment]
What does it mean for a Dirichlet character to be even here (http://www.wstein.org/papers/j1p/12.pdf) in Conjecture 6.2.2 (pg. 62 of pdf)?

**Comment by williamstein** [comment]
I guess you deleted this but if not see
https://en.wikipedia.org/wiki/Dirichlet_character

On Fri, Jul 8, 2016 at 4:19 PM, Kevin Lui notifications@github.com wrote:

> What does it mean for a Dirichlet character to be even here (
> http://www.wstein.org/papers/j1p/12.pdf) in Conjecture 6.2.2 (pg. 62 of
> pdf)?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/williamstein/sage_modabvar/issues/6#issuecomment-231494930,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABN5dlQgQ4bVI6IHnaf0Jlkw027yLgdDks5qTtsdgaJpZM4IxtQD
> .

## 

William (http://wstein.org)
